steps:

# Step 1: Scan the container image with AccuKnox
- name: 'accuknox/accuknox-container-scan'
  id: 'accuknox-container-scan'
  args:
    - 'image'
    - '--format'
    - 'json'
    - '--output'
    - '/workspace/accuknox-report.json'
    - '${_IMAGE_URL}:${_IMAGE_TAG}'

# Step 2: Upload report to GCS
- name: 'gcr.io/cloud-builders/gsutil'
  id: 'upload-report-to-gcs'
  args:
    - 'cp'
    - '/workspace/accuknox-report.json'
    - 'gs://artifacts.shaped-infusion-402417.appspot.com/security-reports/accuknox-report.json'
  waitFor:
    - 'accuknox-container-scan'

# Step 3: Print report
- name: 'ubuntu'
  id: 'print-report'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cat /workspace/accuknox-report.json
  waitFor:
    - 'accuknox-container-scan'

# Step 4: Read AccuKnox token secret
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'access-secret'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud secrets versions access latest \
      --secret=accuknox_token \
      --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/decrypted-data.txt

# Step 5: Upload report to AccuKnox SaaS
- name: 'gcr.io/cloud-builders/curl'
  id: 'forward-result-to-accuknox-saas'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      TOKEN=$$(cat /workspace/decrypted-data.txt)

      echo "Uploading report to AccuKnox SaaS..."

      curl -v --location --request POST \
      "https://${_CSPM_URL}/api/v1/artifact/?label=${_LABEL}&data_type=TR&save_to_s3=false" \
      --header "Authorization: Bearer $${TOKEN}" \
      --header "Content-Type: multipart/form-data" \
      --form "file=@/workspace/accuknox-report.json"
  waitFor:
    - 'access-secret'
    - 'accuknox-container-scan'

# Step 6: Fail if CRITICAL vulnerabilities exist
- name: 'ubuntu'
  id: 'policy-check'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if grep -q "CRITICAL" /workspace/accuknox-report.json; then
        echo "CRITICAL vulnerabilities detected."
        exit 1
      else
        echo "No CRITICAL vulnerabilities detected."
      fi
  waitFor:
    - 'forward-result-to-accuknox-saas'

substitutions:
  _IMAGE_URL: 'nginx'
  _IMAGE_TAG: 'latest'

  _CSPM_URL: 'cspm.demo.accuknox.com'

  _LABEL: 'gcb-container-scan'

options:
  logging: CLOUD_LOGGING_ONLY
